services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  server:
    build: ./server
    image: hadarisas/elasticsearch-demo-server:1.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "3001:3001"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  client:
    build: ./client
    image: hadarisas/elasticsearch-demo-client:1.3
    ports:
      - "8080:80"

volumes:
  elasticsearch-data:
